### PR TITLE
Add cluster configs: default, hardened with split ingress

### PR DESCRIPTION
**Pull request by pli01**
- Add cluster configs file: default ready to use, hardened with split ingress
- Add cheat-sheet doc

### CODE REVIEW

**Comment by rouja** [comment]
Hi,

What do you think to modify cluster-local.sh to be abble to chose between the type of cluster when we use it ?

**Comment by pli01** [comment]
> Hi,
> 
> What do you think to modify cluster-local.sh to be abble to chose between the type of cluster when we use it ?

It would be good.

Unless you want a self-sufficient script installable via "curl |bash" without git clone the repo 
```
curl -OL https://raw...../local-cluster.sh | bash
```

**Comment by rouja** [comment]
This behaviour is absolutely not mandatory.

**Comment by pli01** [comment]
Now  local-cluster.sh use `clusters/default.yaml`

**Review by rouja — APPROVED** [review]
LGTM

**Pull request merged**
